### ISSUE TITLE
'I am ready' error message

### ISSUE THREAD

**Issue by jacobstringer** [Massey-7-Wonders-project-team/Massey_Project_7_Wonders#82] opened 2017-09-21 01:58 UTC
Each time we click 'I am ready', it still shows up that 'There was an error' and polling and the game doesn't start until I force refresh the browser. On the API gateway on the backend, it will send that error message if there is an error on this side so I thought it was that, but it also should print an error message on the console, which isn't happening. So I think somewhere on the front end at that point, we might be looking at a semantic error in the code.

**Comment by Marthijn-B** [comment] 2017-09-21 08:25
I have been trying to locate the "I am Ready" issue... It happened once tonight, and I tried to isolate it, but hasn't happened again no matter how many times I reset the game, server. It's very odd!

**Comment by jacobstringer** [comment] 2017-09-21 09:51
It's happened every time for me so far. Once everything is merged, I will do a clean upload of the master - I've been having problems with pycharm jumping around between versions so I might see if I can start from scratch and see if that was causing the problem.

**Comment by mmdonaldson** [comment] 2017-09-24 04:10
Closing because we can't reproduce

**Closed as completed by mmdonaldson** 2017-09-24 04:10 UTC
Labels: bug
